### ISSUE TITLE
Disk persistence

### ISSUE THREAD

**Issue by kolinkrewinkel** [kumpelblase2/Remote-Entities#27]
Currently there's no form of generalized disk persistence, which should probably happen alongside world-save. The only way I see doing this (and I come from an Objective-C background, so bear with me) is to use a "Persistable" interface, and archive as much as possible, recursively, per plugin, per world, etc, or to use Java's Persistence APIs. From there, saving attributes about them is pretty easy, but string method invocation will have to be used for event handlers, or using a generic instantiable, nameable, event handler class. Example: addBehaviour(new InteractBehavior(entity, MyPersistentEventHandler.class), which the person puts their code to run in each class in some generic function, like Runnable. Will work on it in my fork, starting with humans and interaction events. Only thing I'm unsure of is if it's possible to instantiate a class from the Remote-Entities lib that is "owned" by another package. (Edit, nvm, googling says dynamic references don't need importing, so we just need to ensure it implements the basic run methods/interface. http://www.avajava.com/tutorials/lessons/how-do-i-instantiate-an-object-of-a-class-via-its-string-name.html)

This feels like a rant now, time for sleep.

**Comment by IDragonfire** [comment]
Atm. the plugin that creates the RemoteEntitiy must store/and restore it.

**Comment by kolinkrewinkel** [comment]
Yep, but it'd be ideal to decouple that requirement.

**Comment by IDragonfire** [comment]
The problem is to find a good way to save the Entities and to reload them, including to inform all plugins: "Here is your entitiy".
It is possible, but I think cost and benefits stands in no relation. 
That is my opinion, maybe kumpelblase has another..
I am sure, if you write a good solution, kumpelblase accepts the pull request ;)

**Comment by IDragonfire** [comment]
I had the same ideas for RepeatingTasks (store tasks that should be executed long time in the future on disk and auto save/load tasks)...
Take a look at DragonTimer ...
I choosed a XML storage format ...

**Comment by kumpelblase2** [comment]
Persistance is something I though about from the start, however, I haven't gotten a good answer to this question for myself for a long time and thus I've put it on the side. The reasons why I don't have a good answer are pretty small, but still prevent me from finding a solution. Starting off, since these are still minecraft entities, I could leave it to the world to save them. However, I can't save additional stuff and I have no idea how loading them back on my own would work. Secondly, there are so many ways of saving them otherwise. Because of that, every developer uses a different way. YML and MySQL are probably the most famous for bukkit, but I for example would also like to use JSON because it's really easy to implement in java. Someone could now say "So what's the problem? Choose the way you like and everything is fine!". No, that's wrong. I've made this library with extendability in mind, so people could change, add or modify everything easily. When I should now choose which way for saving I'd go, I'd limit other people in adding their own data to it or make it more complicated as when they'd have done it on their own.
If I would have a proper answer, I wouldn't have released it until that part was done. The actual implementation won't be and is not the problem; figuring out a way so everyone is happy is.
I'll get back to my board soon to find a good solution and I'll also take a look at your approach.

~kumpelblase2.

**Comment by kolinkrewinkel** [comment]
Cool. As far as extensibility goes, I'm a big fan of the Java Persistence API or something like Apple's NSCoding protocol. https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Protocols/NSCoding_Protocol/Reference/Reference.html optional, easy to implement as a third party, and pretty easy to add in the first-party internals.

**Comment by IDragonfire** [comment]
In my opinion the problem is not the case to save the data ... Java Persistence API makes it for you,
the problem is to defines Interface for loading the objects ...
If you have your own RemoteEntity you must notify the Plugin ...
If I understand it right, "encodeWithCoder" must notify the Plugin: "Here I am the loaded Entity, manage me"

**Comment by kolinkrewinkel** [comment]
Yes, the coder provides context. As an example, a class implements NSCoding, just like saying a Java class implements Runnable. A root class handles the trigger for the encoding, at which point the process chains down recursively.

As an example:

World save notification -> Entity manager -> Create/load a coder object representing a file of whatever type, preferably JSON, and could be as simple as convenience methods on something like FileConfiguration -> Let the manager clear the saved attributes for the world -> enumerate through each entity managed in that world (filter out anything that isn't in the world that saved) -> tell them to encode to that coder, which subsequently modifies the object which, when the recursive process is done, is saved by the disk.

If we make this fast and efficient enough, it won't even have to notify, just optionally post listeners. Otherwise, we act like they were always there...

**Comment by IDragonfire** [comment]
Can you give an example, how to load an Entitiy?

**Comment by kolinkrewinkel** [comment]
Something along the lines of (within the instantiation method EntityManager): { this.coder = new EntitiesCoder(this, this.plugin, "archived.json"); this.coder.loadEntitiesForAllWorlds(). } Within the coder method, it would probably unpack the data into Java level objects, at which point we can re-instantiate the entities (at least with as much information available). From here, we can pass them back to RemoteEntities, (this.manager.beginManagingRemoteEntity(assembledEntity). Provided this happens synchronously, it'll be like nothing happened. Hopefully tomorrow or the day after (re: screw you, school) I'll have time to work on some real code — at least creating the interfaces and skeleton functions.

**Comment by IDragonfire** [comment]
k, we have the same idea :)
Only names differ ...
Maybe we can create some interfaces/UML diagrams to make it clear.
My first draft was:
http://img844.imageshack.us/img844/1460/1358931720949.jpg
![image](https://f.cloud.github.com/assets/1217999/89379/bfa42074-653b-11e2-8942-c5edb7f680f8.jpg)

**Comment by kumpelblase2** [comment]
Since I have a day off school, I did some thinking on it. (I hope you can read the text on the images, I know I have a crappy handwriting)
I though about a serializer looking something like this: https://dl.dropbox.com/u/15011952/remote_entities/serializer.jpg
I will probably get registered in the plugins entitymanager either at the time of creation or directly after that.
There will be two which remote entities will provide by itself, the JSON- and YML-serializer (maybe also a mysql one...) Since I love json, I already made up the structure for the json file afterwards: https://dl.dropbox.com/u/15011952/remote_entities/entities.jpg and https://dl.dropbox.com/u/15011952/remote_entities/behaviors.jpg I know that the desires and behaviors should actually be included in the entities.json so it'll be easier to track which behavior goes to which entity.

To load/save them on your will, there'll be methods provided in the entitymanager and the remote entity itself.
e.g. RemoteEntity.save(), EntityManager.saveAll() and others.

**Comment by IDragonfire** [comment]
Looks good, basicly same idea ...
@EntitySerializer:
I love the idea to have an interface, because I prefer XML storage ...
e.g. look at: http://xstream.codehaus.org/tutorial.html
I try different storage techniques (see https://github.com/IDragonfire/DragonTimer/commits/master)
and these was the fastest and easiest library^^

Ps.: Why need the Serializer constructure a plugin object? In my first storage library I also use the plugin,
but it is not neseccary, because an ID, e.g. pluginname is enough. If you want version, extends the pluginname ;)

If I am at home, I post an possible output of an XML file of RemoteEntitiy ;)

Edit: I try to save all informations first ... file was 95MB big xD
XStream also allows JSON output :)

**Comment by IDragonfire** [comment]
Devs can extends the EntityData and store there own data for customs Entities ...
I love the idea :)

**Comment by kumpelblase2** [comment]
That's exactly what I was aiming at.
However, we might want to go with GSON as a json parser as it's already included in craftbukkit (at least it used to).

**Comment by kolinkrewinkel** [comment]
Per your whiteboard drawings, one thing I'd suggest about the data structure would be to have the plugin names be the top tier, with config and entities as children. Matches the existing paradigm with the managers.

**Comment by kumpelblase2** [comment]
I didn't include one picture because I didn't though it would be necessary. When you use the serializers provided by the library and don't specify a specific save path, they'll get saved in <plugins_folder>/RemoteEntities/<plugin>/<file>.json . The reason why I didn't included it was that people will probably extend the existing ones what so ever and thus will probably let them get saved in their plugins folder. This is at least how I would imagine/like it.

**Comment by kolinkrewinkel** [comment]
What I meant was that it would be com.kolinkrewinkel.plugin { config {}, entities {}, ...} that way it'd be fetch able by plugin, as it should when the plugin instantiates its EntityManager.

**Comment by IDragonfire** [comment]
Each Plugin must extend the EntityData and these Container can store everything,
if somebody try to save the EntityManager, the size of the file exploded xD

**Comment by kolinkrewinkel** [comment]
My example was within the RemoteEntities.json file: 

``` java
{
   com.kolinkrewinkel.BitLimitNPCs {
       config {
           remove_when_dead: true
       },
       entities {
           ...
       }
   },
   com.idragonfire.dragontimer {
       ...
   }
}
```

**Comment by kumpelblase2** [comment]
The reason I don't want to have it one file is that it will be pretty hard to handle in cooperation with the parser. In your example I'd need to get the individual parts for the plugin by myself and then pass them over to the plugin parsers. When there would be separate files, we could just hand them the individual parsers without the need to separate the parts in the first place.
It would be fine if we don't allow custom data to be in there because then we can easily parse it on out own. Having them separated in their own "space" makes it also a lot more organized if they add more files for their entities.

**Comment by kumpelblase2** [comment]
I made a separate branch for testing my serializer implementation.
https://github.com/kumpelblase2/Remote-Entities/tree/persistence

EDIT: At this point I think I could pull the stuff over to the master branch. However, I would be nice if someone could give some feedback and/or test these things out (e.g. custom entity data with the json serializer).

**Comment by IDragonfire** [comment]
I don't understand, why did you make it so complicated and static?

**Comment by kumpelblase2** [comment]
I don't think it's complicated. I find it fairly simple and really extensible.

**Comment by kolinkrewinkel** [comment]
Do you guys think my fork/PR is still headed in the right direction?

**Comment by kumpelblase2** [comment]
I don't think there'll be a right or wrong direction or way of doing it. However, I would say there are some certain aspects we need to think about a lot more. The thing that is bothering me and probably also you is the dynamic creation of the desires. It is not really easy to save the parameters in a file because well... those most likely aren't just strings we can save. Enums, classes and even instances of mobs are used. I for myself don't really find it ideal to add a serialize method to every single desire (one in the base class would be what I'm aiming for and only special ones override it). Today is not really a good day for me to think about that as I have a lot to do, so I'll have to wait until at least tomorrow to get my head wrapped around this.

**Comment by kolinkrewinkel** [comment]
Good stuff you've got going in the persistence branch.

**Comment by kolinkrewinkel** [comment]
Just as a note: to get what I needed done quickly, I did a hackjob solution in my most recent commit (https://github.com/kolinkrewinkel/Remote-Entities/commit/6bb3a9009c9e08b8cb20e591f19dc6089285d4f3). Not a real fix as it's totally one-off, but worth noting that there needs to be a solution for clearing the behaviors. It's easy to not clear them, but then you also need to reinform them if you keep them around and change out their entity from beneath their feet.
