### ISSUE TITLE
RightClick not working

### ISSUE THREAD

**Issue by IDragonfire** [kumpelblase2/Remote-Entities#51]
rightClick on a remote entity fire no RemoteEntityInteractEvent

**Comment by IDragonfire** [comment]
To listen for a rightclick on a remote entity, please listen to a "PlayerInteractEntityEvent" bukkit event.
@kumpelblase2:
There is no way to react before the Bukkit-Event:
https://github.com/Bukkit/CraftBukkit/blob/master/src/main/java/net/minecraft/server/PlayerConnection.java#L1079

**Comment by kolinkrewinkel** [comment]
Confirmed: this doesn't work properly. Left clicking fires the event. Any idea why? I looked at the superclass's implementation of a(EntityHuman e) and it appeared to be for left click behavior. Using the InteractEntityEvent doesn't work because if the named entities have the same name, CraftBukkit returns only one instance—not the right one. No idea why. Any ideas on how to fix it from left-> right click? The CraftBukkit stuff makes my head hurt...

**Comment by kumpelblase2** [comment]
Could you test the latest build? I tried to fix it (but it might fail due to some other changes I made)

**Comment by kolinkrewinkel** [comment]
Did not work. Not sure if it's the implementation or the related changes, but upon experimenting with the various alphabet methods (a(), b(), etc.) methods and a bit of digging, I don't really see a place that the entity gets notified that it was interacted with, oddly. (Maybe I'm just missing something though.)
