### ISSUE TITLE
Custom desire (DesireMoveToLocation subclass) failing in 1.8-SNAPSHOT (works in 1.7)

### ISSUE THREAD

**Issue by desht** [kumpelblase2/Remote-Entities#61]
See https://github.com/desht/ChessCraft/blob/master/src/main/java/me/desht/chesscraft/chess/pieces/EntityChessStone.java

Basically, I'm adding a custom desire (a subclass of DesireMoveToLocation) to an entity to make it move to a given location, and possibly remove another entity when it gets there.  See the constructor for DesireMovePiece at line 79 of the above class.

In RemoteEntities 1.7 this works, and the entity moves as expected.  In the 1.8-SNAPSHOT that I downloaded yesterday, the entity takes a couple of steps, and then just walks round in a circle indefinitely.

(The call to entity.teleport(realDest) seems to be necessary to ensure the piece is properly centred on its board square - without it, the entity seems to overshoot the target location slightly - not sure if that's a problem or normal behaviour, but it's separate to this particular issue).

**Comment by kumpelblase2** [comment]
Wow, I shouldn't rely on email notifications, never saw this, I'm really sorry. Since a lot of things have changed, I don't know if something already fixed it or not. It might a bit too much to ask, but could you try it again and see if that behavior is still there?
(I'm closing this for now, feel free to reopen it.)
