### ISSUE TITLE
License questions

### ISSUE THREAD

**Issue by joshcough** [kumpelblase2/Remote-Entities#83]
Hello, 

I have forked this project, but after reading your license, I am confused if I'm even allowed to. My end goal is simply to use it to spawn, teleport, remove NPCs for a Minecraft-NetLogo integration project I've been working on. Additionally, I would like to convert it to Scala (probably not all at once), and publish it to bintray so that I can reference it as a dependency from my project. Having my own fork in Scala will allow me the flexibility to update and publish it quickly, and allow me to drop parts of the api that I am not using. 

However, I am finding your license to be difficult to understand, and quite restrictive, and I'd like to ask a few questions about it. 

1)  When you say, "When redistributing the modified product you need the permission of the   author of the original product.", depending on what the definition of 'redistribute' is, I'm not even sure that allows me to fork the repo, let alone publish anything to bintray. Forking could be considered 'redistributing' it under my github account. I would like to keep my fork and publish to bintray, so I am asking for permission and/or clarification.

2) Bintray requires known licenses, and it seems as if yours is written by hand. If I am allowed to publish the Scala version, would it be alright if I use the MIT license if I also reference your project and original license?

I have no intention of profiting, or even gaining notoriety from forking this project. I just find parts of it very useful for a fun project that I am working on, but I've noticed your code hasn't been updated in two months and I'd like to take it and use it. 

Thank you.

-Josh

**Comment by kumpelblase2** [comment]
Thanks for bringing this up. I hope I changed the license to make things more clear.

A (private/public) fork on github is allowed and I'm in full support of this. With 'redistribution' I was refering to redistributing a compiled package, thus a .jar for example, of Remot Entities, not the modified source directly.

When making a fork or deriviation of the source of Remote Entities just make sure that it's clear that the original is this / I'm the original author of the work. If you do a fork over github, it already mentions from where it is forked and thus this limitation is already fulfilled.

If you convert it to scala, or generally any other language, it will end up as a -completely- different product and thus is no longer bound to this license. You then may chose your own license of choice.

This hopefully makes things clear for you. I'm leaving this open if you have any further questions, otherwise it would be nice of you to close it.
~kumpelblase2.

**Comment by joshcough** [comment]
Thank you for the reply and for updating the license. I think only one thing that remains unclear.

Can I publish the binary to bintray after some modifications, but without converting the code to Scala, and can I change the license to MIT before that time? For example - I've already removed 'thinking' because I didn't need it. Converting code to Scala will take much longer, and I could use the binary before that time. I'm not sure if this is allowed under your license, but if not, I'm asking for a one time exception.

Thanks again. I will close the issue after you reply.

-Josh

**Comment by kumpelblase2** [comment]
I would allow you to do that in this case, yes.

**Comment by joshcough** [comment]
Thank you. Closing.
